### ISSUE TITLE
Image version ?

### ISSUE THREAD

**Issue by batleforc** [che-incubator/jetbrains-ide-dev-server#1]
Hi, 
I've seen that you are working on https://github.com/redhat-developer/devspaces-gateway-plugin to facilitate the connection process to the ide but is it possible to have a build of the one with all the command in the meantime ?

**Comment by azatsarynnyy** [comment]
Hi @batleforc 
you can test the plugin by installing it from the zip https://github.com/redhat-developer/devspaces-gateway-plugin/releases/tag/v0.0.1

**Comment by batleforc** [comment]
Hi @azatsarynnyy 
Thanks for the reply, I tried the extension. The quick link (jetbrains-gateway://connect#type=devspaces&dwNamespace& etc...) doesn't work for me, but the connect from the extension is working (is it possible to use the kubectl cred ?).
Just the window used to connect to the ide that is stuck and fully grey once minimized.
I know that it's the very early phase but thanks it will make a lot of thing easier.

**Comment by azatsarynnyy** [comment]
@batleforc Thanks a lot for testing the extension ❤️ 
You're right - it's in a very early stage and it requires fixing the bugs. And thank you for reporting them here 👍 It helps us a lot with improving the plugin.

> Just the window used to connect to the ide that is stuck and fully grey once minimized.

Let's discuss them one by one.

**1. As for the quick link...**

Could you share how exactly you use it?
We haven't documented the plugin usage yet. But it should work as follows:
a) log in to your server with the `oc login`
b) run your Workspace from the Dashboard
c) use the `Open Gateway` button suggested by your browser

The connection should be established even without the need to know about the quick link. See a short screencast I attached here https://github.com/redhat-developer/devspaces-gateway-plugin/pull/23

**2. `kubectl` cred usage**

I haven't tried it with `kubectl`. But the flow, I described above, should work perfectly with the `oc` client. Is it important for your use case to use `kubectl` instead of `oc`?
If you're talking about skipping the first step of the wizard (login in), AFAIK @tolusha already working on that.

**3. the stuck grey window**

I'm not sure I understand the steps correctly. It would help me to check it if you could share a short screencast or the exact steps to reproduce the issue.

**4. it didn't stop the ide on exit**

I've also noticed this problem. In my case, the workspace was stopped, but it took a few minutes for some reason 🤷‍♂️ 
FYI @tolusha ^^

**Comment by azatsarynnyy** [comment]
@batleforc we've just discussed items 2 and 4 with @tolusha 
There are updates on these items:
**2.** With https://github.com/redhat-developer/devspaces-gateway-plugin/pull/33 merged, the login credentials will be loaded from the `.kube/config`.
**4.** Currently, it takes some time to get a notification from the IDEA server about stopping the backend. We'll look at how it can be improved.

**Comment by batleforc** [comment]
1. I followed the same process, but after the redirect i ended with a "there was an error in a connection provider" => "No connection handler was returned". When looking in the log i find a "unable to find valid certification path to requested target"

2.  🎉 🎉 🎉 , it wasn't in the use of the kubectl only (even if i'm thinking of using it with eclipse che) but in order to skip the windows that ask for the api/token.

3. i will work on it when i can

Thanks for your work on this project, I really like using it has my main env.

**Comment by azatsarynnyy** [comment]
> 3. i will work on it when i can
> 

it would be great, any contributions are warmly welcomed 😉

**Comment by batleforc** [comment]
For the 3 i couldn't make a screen cast but here are the step:

1. Start the workspace from console
2. Start JetBrains gateway
3. Select "Connect to Dev Spaces"
4. Provide the auth information
5. Select the workspace to use
6. The new ide windows start but the old one stay and is fully brown

**Comment by azatsarynnyy** [comment]
@batleforc oh.. I see. You mean the Gateway app window hangs, right? Not the Thin Client window (IDE itself). Am I correct?

**Comment by batleforc** [comment]
@azatsarynnyy  Yes you are, the true problem behind it is that i have to force shutdown it after

**Comment by batleforc** [comment]
Hi, 
Any update ?

**Comment by azatsarynnyy** [comment]
Hi @batleforc 
@tolusha is working on it

**Comment by azatsarynnyy** [comment]
The issue was fixed in https://github.com/redhat-developer/devspaces-gateway-plugin/pull/37
